# Azure Deployment Workflow - Preparado para Sprint 7
# Este workflow está listo para activarse una vez completada la configuración manual
# Estado: ESQUELETO (Sprint 6) → ACTIVO (Sprint 7)

name: Deploy to Azure App Service

# Temporalmente desactivado - activar en Sprint 7
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

env:
  AZURE_WEBAPP_NAME: crm-basico-app
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  NODE_VERSION: '18.x'

jobs:
  # Job preparado para testing
  test:
    name: 'Test and Validate'
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    
    steps:
    - name: 'Checkout code'
      uses: actions/checkout@v4
    
    - name: 'Setup Node.js'
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: 'Install dependencies'
      run: npm ci
    
    - name: 'Run tests'
      run: npm test
    
    - name: 'Sprint 6 Status'
      run: |
        echo "🚀 Workflow preparado para Sprint 7"
        echo "📋 Configuración manual debe completarse primero"
        echo "✅ Deploy automático se activará en próximo sprint"

  # Placeholder para deploy job
  deploy-info:
    name: 'Deployment Info'
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: 'Deployment Status'
      run: |
        echo "Environment: ${{ github.event.inputs.environment }}"
        echo "Status: Preparado para Sprint 7"
        echo "Next: Configurar Azure credentials y activar deploy real"
